### ISSUE TITLE
Bounding Box?

### ISSUE THREAD

**Issue by btupper** [SeascapeScience/Calanus#1]
@SeascapeScience   What should the bounding box be?  

It looks like in the paper it is ...
left = -72, right = -42, bottom = 40, top = 60

But the email graphic from Kathy M looks biggerer.

**Comment by SeascapeScience** [comment]
Kathy wants a bigger bounding box. One that includes the whole Gulf of Maine, and goes up to Greenland.

**Comment by btupper** [comment]
So...  Greenland is sort of big. Maybe...

-72 to  -40  (Vt to right of southern Greenland)
40 to 70  (south of Cape Cod to Disko Island

**Comment by btupper** [comment]
![bb](https://user-images.githubusercontent.com/5097791/50178971-e1bb1500-02d3-11e9-852a-64356abfdf1c.png)

**Comment by SeascapeScience** [comment]
Looks good. How about I run it by Kathy.

**Comment by SeascapeScience** [comment]
...go with that, and I'll let you know if she wants it changed.

**Comment by SeascapeScience** [comment]
Kathy confirms, this is the right bounding box for the salmon project.
