### ISSUE TITLE
Lump Cfin_CV and Cfin_CVI?

### ISSUE THREAD

**Issue by btupper** [SeascapeScience/Calanus#2]
I know you mentioned this, but I can't recall what you decided.  Is Cfin abundance to be just CV or CV+CVI?

**Comment by btupper** [comment]
Ooops.  Now I see that it is just stage V.  Doh.

FYI - the paper lumps V and VI together for Cfin.

**Comment by btupper** [comment]
No.  They lump IV + V + VI as one.  Sigh.

Make me stop.

**Comment by SeascapeScience** [comment]
Can we leave it as CV to start with, but leave it as an option?

**Comment by btupper** [comment]
Yes - everything is an option anyways, but we'll default to V.  Once I fix that up we are ready to rock.
